### ISSUE TITLE
CSS spinner

### ISSUE THREAD

**Issue by kjakobson** [cesko-digital/join.cesko.digital#5]
inspirace- https://projects.lukehaas.me/css-loaders/
použít jako primary color #080831
width 2px

**Comment by kjakobson** [comment]
+ schovat checkbox "osobní údaje" a zakomentovat validaci

**Comment by radkoa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [👥 odebrat zaškrtávací políčko se souhlasem se zpracováním údajů -> GitHub](https://trello.com/c/FzVZoxRK/61-%F0%9F%91%A5-odebrat-za%C5%A1krt%C3%A1vac%C3%AD-pol%C3%AD%C4%8Dko-se-souhlasem-se-zpracov%C3%A1n%C3%ADm-%C3%BAdaj%C5%AF-github)
