### ISSUE TITLE
Doplnit CONTRIBUTING.md

### ISSUE THREAD

**Issue by radkoa** [cesko-digital/join.cesko.digital#7]
Vzhledem k tomu, že se snažíme být maximálně kompatibilní s redesignem webu Česko.Digital, mělo by stačit použít https://github.com/cesko-digital/web/blob/rework/CONTRIBUTING.md. V případě potřeby ho můžeme lehce upravit. Je to tak @kjakobson?

**Comment by kjakobson** [comment]
Je to tak, ale navíc tu máme api - celou složku /api jsem pro všechny tooly na linting dal do ignore. Nevím jak tohle řešit když to není vyloženě monorepo a nemůžeme pro /api mít vlastní nastavení a codestyle. Normálně bych to neřešil a dal tam to samé co máme pro web protože to je standard pro JS, ale nechci do toho Pavlovi zasahovat.

**Comment by bver** [comment]
Jakube, klidně zasahuj, já jsem teď trochu zaneprázdněný a vrátím se k věci někdy během příštího týdne.
Samozřejmě to pak můžu vyčistit, možná issue na mou hlavu?

**Comment by kjakobson** [comment]
Ok tak to zkusíme a uvidíme, vždycky to můžeme vypnout.

**Comment by kjakobson** [comment]
@radkoa navrhuju vyhnout se tomu že to budeme kopírovat, když můžeme použít link na původní web verzi. Cílem je stejně to jednou dostat do monorepa s hlavním webem. Rozhodně by to bylo z pohledu vývoje nejlepší.
